{
  "swagger": "2.0",
  "info": {
      "version": "1.0",
      "title": "Patta API",
      "description": "Patta is address book of Pakistan"
  },
  "host": "patta-api.dscvu.com",
  "basePath": "/v1",
  "schemes": [
      "https"
  ],
  "consumes": [
      "application/json"
  ],
  "produces": [
      "application/json"
  ],
  "securityDefinitions": {
      "Authorization": {
          "name": "Authorization",
          "type": "apiKey",
          "in": "header"
      }
  },
  "paths": {
      "/auth/sign_up": {
          "post": {
              "operationId": "POST_auth-sign_up",
              "summary": "Sign Up",
              "tags": [
                  "Auth"
              ],
              "parameters": [
                  {
                      "name": "body",
                      "in": "body",
                      "schema": {
                          "$ref": "#/definitions/input-sign-up",
                          "example": {
                              "email": "sulmanweb@gmail.com",
                              "password": "abcd1234",
                              "name": "Sulman Baig"
                          }
                      }
                  }
              ],
              "responses": {
                  "201": {
                      "description": "",
                      "schema": {
                          "$ref": "#/definitions/output-sign-in"
                      },
                      "examples": {
                          "application/json": {
                              "Authorization": "Bearer endkjenkjededehjbjnkhbwebhcyebdcgv",
                              "user": {
                                  "id": 123,
                                  "email": "sulmanweb@gmail.com",
                                  "name": "Sulman Baig",
                                  "admin": false,
                                  "created_at": "2019-06-28T08:48:12.949Z",
                                  "confirmed": true
                              }
                          }
                      }
                  },
                  "400": {
                      "$ref": "#/responses/trait:appErrors:400"
                  },
                  "401": {
                      "$ref": "#/responses/trait:appErrors:401"
                  },
                  "403": {
                      "$ref": "#/responses/trait:appErrors:403"
                  },
                  "404": {
                      "$ref": "#/responses/trait:appErrors:404"
                  },
                  "421": {
                      "$ref": "#/responses/trait:appErrors:421"
                  },
                  "422": {
                      "$ref": "#/responses/trait:appErrors:422"
                  },
                  "500": {
                      "$ref": "#/responses/trait:appErrors:500"
                  },
                  "501": {
                      "$ref": "#/responses/trait:appErrors:501"
                  }
              }
          }
      },
      "/auth/sign_in": {
          "post": {
              "operationId": "POST_auth-sign_in",
              "summary": "Sign In",
              "tags": [
                  "Auth"
              ],
              "parameters": [
                  {
                      "name": "body",
                      "in": "body",
                      "schema": {
                          "$ref": "#/definitions/input-sign-in",
                          "example": {
                              "email": "sulmanweb@gmail.com",
                              "password": "abcd1234"
                          }
                      }
                  }
              ],
              "responses": {
                  "201": {
                      "description": "",
                      "schema": {
                          "$ref": "#/definitions/output-sign-in"
                      },
                      "examples": {
                          "application/json": {
                              "Authorization": "Bearer endkjenkjededehjbjnkhbwebhcyebdcgv",
                              "user": {
                                  "id": 123,
                                  "email": "sulmanweb@gmail.com",
                                  "name": "Sulman Baig",
                                  "admin": false,
                                  "created_at": "2019-06-28T08:48:12.949Z",
                                  "confirmed": true
                              }
                          }
                      }
                  },
                  "400": {
                      "$ref": "#/responses/trait:appErrors:400"
                  },
                  "401": {
                      "$ref": "#/responses/trait:appErrors:401"
                  },
                  "403": {
                      "$ref": "#/responses/trait:appErrors:403"
                  },
                  "404": {
                      "$ref": "#/responses/trait:appErrors:404"
                  },
                  "421": {
                      "$ref": "#/responses/trait:appErrors:421"
                  },
                  "422": {
                      "$ref": "#/responses/trait:appErrors:422"
                  },
                  "500": {
                      "$ref": "#/responses/trait:appErrors:500"
                  },
                  "501": {
                      "$ref": "#/responses/trait:appErrors:501"
                  }
              }
          }
      },
      "/auth/validate_token": {
          "get": {
              "operationId": "GET_auth-validate_token",
              "summary": "Validate Auth Token",
              "tags": [
                  "Auth"
              ],
              "description": "Returns User or gives error.",
              "responses": {
                  "200": {
                      "description": "",
                      "schema": {
                          "$ref": "#/definitions/output-sign-in"
                      },
                      "examples": {
                          "application/json": {
                              "Authorization": "Bearer endkjenkjededehjbjnkhbwebhcyebdcgv",
                              "user": {
                                  "id": 123,
                                  "email": "sulmanweb@gmail.com",
                                  "name": "Sulman Baig",
                                  "admin": false,
                                  "created_at": "2019-06-28T08:48:12.949Z",
                                  "confirmed": true
                              }
                          }
                      }
                  },
                  "400": {
                      "$ref": "#/responses/trait:appErrors:400"
                  },
                  "401": {
                      "$ref": "#/responses/trait:appErrors:401"
                  },
                  "403": {
                      "$ref": "#/responses/trait:appErrors:403"
                  },
                  "404": {
                      "$ref": "#/responses/trait:appErrors:404"
                  },
                  "421": {
                      "$ref": "#/responses/trait:appErrors:421"
                  },
                  "422": {
                      "$ref": "#/responses/trait:appErrors:422"
                  },
                  "500": {
                      "$ref": "#/responses/trait:appErrors:500"
                  },
                  "501": {
                      "$ref": "#/responses/trait:appErrors:501"
                  }
              },
              "security": [
                  {
                      "Authorization": []
                  }
              ]
          }
      },
      "/auth/destroy": {
          "delete": {
              "operationId": "DELETE_auth-destroy",
              "summary": "Destroy Self User",
              "tags": [
                  "Auth"
              ],
              "description": "Destroys the logged-in user from the system.",
              "responses": {
                  "204": {
                      "description": ""
                  },
                  "400": {
                      "$ref": "#/responses/trait:appErrors:400"
                  },
                  "401": {
                      "$ref": "#/responses/trait:appErrors:401"
                  },
                  "403": {
                      "$ref": "#/responses/trait:appErrors:403"
                  },
                  "404": {
                      "$ref": "#/responses/trait:appErrors:404"
                  },
                  "421": {
                      "$ref": "#/responses/trait:appErrors:421"
                  },
                  "422": {
                      "$ref": "#/responses/trait:appErrors:422"
                  },
                  "500": {
                      "$ref": "#/responses/trait:appErrors:500"
                  },
                  "501": {
                      "$ref": "#/responses/trait:appErrors:501"
                  }
              },
              "security": [
                  {
                      "Authorization": []
                  }
              ]
          }
      }
  },
  "responses": {
      "trait:appErrors:400": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      },
      "trait:appErrors:401": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      },
      "trait:appErrors:403": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      },
      "trait:appErrors:404": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      },
      "trait:appErrors:421": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      },
      "trait:appErrors:422": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      },
      "trait:appErrors:500": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      },
      "trait:appErrors:501": {
          "description": "",
          "schema": {
              "type": "object",
              "properties": {
                  "errors": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                  "errors"
              ]
          }
      }
  },
  "definitions": {
      "input-sign-up": {
          "title": "input-sign-up",
          "type": "object",
          "properties": {
              "email": {
                  "type": "string",
                  "format": "email"
              },
              "password": {
                  "type": "string",
                  "minLength": 6,
                  "maxLength": 72,
                  "pattern": "^(?=.*[a-zA-Z])(?=.*[0-9]).{6,72}$",
                  "description": "must be 6-72 characters and atleast 1 number"
              },
              "name": {
                  "type": "string",
                  "maxLength": 255
              }
          },
          "required": [
              "email",
              "password"
          ],
          "example": {
              "email": "sulmanweb@gmail.com",
              "password": "abcd1234",
              "name": "Sulman Baig"
          }
      },
      "output-user": {
          "title": "output-user",
          "type": "object",
          "properties": {
              "id": {
                  "type": "integer"
              },
              "email": {
                  "type": "string",
                  "format": "email"
              },
              "name": {
                  "type": "string"
              },
              "admin": {
                  "type": "boolean"
              },
              "created_at": {
                  "type": "string",
                  "format": "date-time"
              },
              "confirmed": {
                  "type": "boolean",
                  "description": "user has confirmed email or not"
              }
          },
          "required": [
              "id",
              "email"
          ],
          "example": {
              "id": 123,
              "email": "sulmanweb@gmail.com",
              "name": "Sulman Baig",
              "admin": false,
              "created_at": "2019-07-14T14:13:53.394Z",
              "confirmed": true
          }
      },
      "output-sign-in": {
          "title": "output-sign-in",
          "type": "object",
          "properties": {
              "Authorization": {
                  "type": "string"
              },
              "user": {
                  "$ref": "#/definitions/output-user"
              }
          },
          "required": [
              "Authorization"
          ],
          "example": {
              "Authorization": "Bearer nkdjnvkjevjfefewfewfewfewfewfewfewfewevvtyhu",
              "user": {
                  "id": 123,
                  "email": "sulmanweb@gmail.com",
                  "name": "Sulman Baig",
                  "admin": false,
                  "created_at": "2019-03-19T21:24:47.326Z",
                  "confirmed": true
              }
          }
      },
      "input-sign-in": {
          "title": "input-sign-in",
          "type": "object",
          "properties": {
              "email": {
                  "type": "string",
                  "format": "email"
              },
              "password": {
                  "type": "string",
                  "minLength": 6,
                  "maxLength": 72,
                  "pattern": "^(?=.*[a-zA-Z])(?=.*[0-9]).{6,72}$",
                  "description": "must be 6-72 characters and atleast 1 number"
              }
          },
          "required": [
              "email",
              "password"
          ],
          "example": {
              "email": "sulmanweb@gmail.com",
              "password": "abcd1234",
              "name": "Sulman Baig"
          }
      }
  }
}
